import "./UnderstandMoreModal.css";

function UnderstandMoreModal({ sourceDetails, selectionReason, onClose }) {
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>

        <button
          className="modal-close-btn"
          onClick={onClose}
          aria-label="Close"
        >
          ✕
        </button>

        <h2 className="modal-title">Trusted Sources</h2>
        <p className="modal-intro">
          This is what verified agricultural guidance says about your situation.
          Use this to prepare questions for your agrovet or extension officer.
        </p>

        {sourceDetails.length === 0 ? (
          <p className="modal-empty-note">
            We don't have verified guidance for this specific situation yet.
            You can still continue the conversation with an agrovet or
            extension officer using your Kagua Summary.
          </p>
        ) : (
          <>
            {/* Why these sources were selected — prefers the case-specific
                reason generated by get_comparison.py (references this
                farmer's actual observations) over the generic fallback,
                which only shows for older saved journeys from before this
                field existed. */}
            <p className="modal-selection-note">
              {selectionReason ||
                "These sources were selected because they discuss symptoms that " +
                  "may relate to the observations you shared. They are provided to " +
                  "help you compare information, not to confirm a diagnosis."}
            </p>

            {sourceDetails.map((source, index) => (
              <div key={index} className="modal-source">
                <h3 className="modal-source-name">{source.name}</h3>
                <p className="modal-source-topic">{source.topic}</p>
                <p className="modal-source-summary">{source.summary}</p>

                {/* Clarifying questions — written in plain farmer language,
                    helps them know what to look for in their field.
                    Collapsed by default via <details> — the farmer opens
                    only the sections she actually wants to read, rather
                    than scrolling past everything expanded. */}
                {source.learning_points && source.learning_points.length > 0 && (
                  <details className="modal-section">
                    <summary className="modal-section-label">
                      Questions to check in your field
                    </summary>
                    <ul className="modal-learning-points">
                      {source.learning_points.map((point, i) => (
                        <li key={i}>{point}</li>
                      ))}
                    </ul>
                  </details>
                )}

                {/* Why information may differ — helps farmer understand
                    why their neighbour and agrovet gave different advice */}
                {source.why_may_differ && source.why_may_differ.length > 0 && (
                  <details className="modal-section">
                    <summary className="modal-section-label">
                      Why advice may differ
                    </summary>
                    <ul className="modal-learning-points">
                      {source.why_may_differ.map((point, i) => (
                        <li key={i}>{point}</li>
                      ))}
                    </ul>
                  </details>
                )}

                {/* Uncertainties — what even trusted sources can't confirm */}
                {source.uncertainties && source.uncertainties.length > 0 && (
                  <details className="modal-section">
                    <summary className="modal-section-label">
                      What remains uncertain
                    </summary>
                    <ul className="modal-learning-points">
                      {source.uncertainties.map((point, i) => (
                        <li key={i}>{point}</li>
                      ))}
                    </ul>
                  </details>
                )}

                <div className="modal-source-actions">
                  {source.link && (
                    <a
                      className="modal-source-link-btn"
                      href={source.link}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      🔗 Read on {source.name}
                    </a>
                  )}
                </div>
              </div>
            ))}
          </>
        )}

      </div>
    </div>
  );
}

export default UnderstandMoreModal;